from tests.ref_tests.general_tests import GeneralRefTests
from tests.ref_tests.basic_resolve_refs import ResolveRefTests
from tests.ref_tests.norecurse_resolve_refs import ResolveRefTests as NorecurseResolveRefTests
from tests.ref_tests.follow_resolve_refs import ResolveRefTests as FollowResolveRefTests
from tests.ref_tests.follow_norecurse_resolve_refs import ResolveRefTests as FollowNoRecurseResolveRefTests
