from .general_tests import GeneralRefTests
from .basic_resolve_refs import ResolveRefTests
from .norecurse_resolve_refs import ResolveRefTests as NorecurseResolveRefTests
from .follow_resolve_refs import ResolveRefTests as FollowResolveRefTests
from .follow_norecurse_resolve_refs import ResolveRefTests as FollowNoRecurseResolveRefTests
